[package]
name = "make_ultra"
version = "0.1.0"
authors = ["CoolOppo <CoolOppo@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
glob = "0.2"

[profile.release]
lto = true
panic = 'abort'
